### ISSUE TITLE
Meeting 1 design changes

### ISSUE THREAD

**Issue by FlyOrBoom** [AHSAppDevTeam/Arcadia-High-Mobile-iOS#21]
- [x] Spacing around the top of the home page needs to be made similar to Android.
- [x] Spacing of articles in Community
- [x] Search button animation
- [x] Reduce size of notification body
- [x] Font change
- [x] Match border radii with Android
- [x] Remove notification body text on the notification page

**Comment by richardwei6** [comment]
- [ ] Spacing around the top of the home page needs to be made similar to Android.

**Comment by richardwei6** [comment]
Will revisit if need be.
