### ISSUE TITLE
Remove Firebase Sign in

### ISSUE THREAD

**Issue by richardwei6** [AHSAppDevTeam/Arcadia-High-Mobile-iOS#22]
By utilizing the ID card feature on the app, users are able to create authentication accounts in our Firebase database. This potentially allows external people to sign in to services like [edit.ahs.app](https://edit.ahs.app) with unauthorized authorization.

**Comment by FlyOrBoom** [comment]
Not an issue. edit.ahs.app also checks against a separate database of editors (https://ahs-app.firebaseio.com/editors.json).
