### ISSUE TITLE
Implement handling of notification data

### ISSUE THREAD

**Issue by richardwei6** [AHSAppDevTeam/Arcadia-High-Mobile-iOS#23]
Implement handling of notification data so that tapping on the notification opens the article page, for instance.

**Comment by FlyOrBoom** [comment]
```{"break":{"scheduleIDs":["","no-school","no-school","no-school","no-school","no-school","weekend","weekend"],"title":"Break"},"collab":{"scheduleIDs":["","regular","regular","late-start","collab","regular","weekend","weekend"],"title":"collaboration"},"collab-long":{"scheduleIDs":["","no-school","regular","late-start","collab","regular","weekend","weekend"],"title":"collaboration + Long Weekend"},"long":{"scheduleIDs":["","no-school","regular","late-start","regular","regular","weekend","weekend"],"title":"Long Weekend"},"opening":{"scheduleIDs":["","no-school","no-school","late-start","regular","regular","weekend","weekend"],"title":"opening"},"pre-holiday":{"scheduleIDs":["","regular","regular","late-start","regular","collab","weekend","weekend"],"title":"pre-holiday"},"regular":{"scheduleIDs":["","regular","regular","late-start","regular","regular","weekend","weekend"],"title":"regular"},"staff":{"scheduleIDs":["","regular","regular","late-start","regular","no-school","weekend","weekend"],"title":"Staff Development"},"summer":{"scheduleIDs":["","summer","summer","summer","summer","summer","weekend","weekend"],"title":"Summer School"},"summer-finals":{"scheduleIDs":["","no-school","finals-12","finals-34","finals-56","no-school","weekend","weekend"],"title":"Finals"},"veterans":{"scheduleIDs":["","regular","regular","late-start","no-school","no-school","weekend","weekend"],"title":"Veterans"},"winter-finals":{"scheduleIDs":["","regular","finals-12","finals-34","finals-56","no-school","weekend","weekend"],"title":"Finals"}}```
